language: java
jdk:
  - openjdk8
services:
  - docker
cache:
  directories:
    - .autoconf
    - $HOME/.m2
before_install:
  - npm i -g npm
script:
  - mvn clean install
  - make docker
after_success:
  - bash <(curl -s https://codecov.io/bash)
